# Generated by Django 3.0.5 on 2020-04-23 06:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('archive_id', models.CharField(default='a174109c-6c75-46a1-92e3-591936578f32', max_length=64, primary_key=True, serialize=False)),
                ('file_full_name', models.CharField(max_length=512)),
                ('archive_name', models.CharField(max_length=512, null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
