# Generated by Django 3.0.5 on 2020-04-25 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='archive',
            old_name='owner_id',
            new_name='owner',
        ),
        migrations.AlterField(
            model_name='archive',
            name='archive_id',
            field=models.CharField(default='10e14830-83ef-43b4-9ae3-ed1336441d52', max_length=64, primary_key=True, serialize=False),
        ),
    ]
