# Generated by Django 3.0.5 on 2020-04-25 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0002_auto_20200425_0426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='archive_id',
            field=models.CharField(default='a6a9d128-f279-435a-89f4-817cfdcbb6c1', max_length=64, primary_key=True, serialize=False),
        ),
    ]
