# Generated by Django 3.0.5 on 2020-04-26 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0003_auto_20200425_0434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='archive_id',
            field=models.CharField(default='b8e0f8a5-dc38-459a-903f-ed9f8b07c45a', max_length=64, primary_key=True, serialize=False),
        ),
    ]
