# Generated by Django 3.0.5 on 2020-04-27 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0004_auto_20200426_0553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='archive_id',
            field=models.CharField(default='c6bb1c01-4b2e-4211-8e2a-76b6722ab7ad', max_length=64, primary_key=True, serialize=False),
        ),
    ]
